Form for testing
TEDx-SJEC/website pull request #14
Opened 2024-09-25 17:07 UTC by joywin2003

2024-09-26 11:41 UTC, Vyshnav001 commented on src/app/actions/get-price.ts
> +  const basePrice = 1000;
better to create a constants file and add all the constants there

2024-09-26 11:50 UTC, Vyshnav001 requested changes

2024-09-26 11:50 UTC, Vyshnav001 commented on src/app/layout.tsx
> +          <Toaster
can u wrap this inside the providers ??

2024-09-26 11:50 UTC, Vyshnav001 commented on src/components/payment.tsx
> +    basePrice: 1200,
use the basePrice from the constants file

2024-09-26 14:28 UTC, joywin2003 commented on src/app/actions/get-price.ts
> +  const basePrice = 1000;
I have added under constants, this should be alright or should i save it somewhere else?
```typescript
// src/constants/index.ts
export const basePrice = 1000;
export const initialDiscount = 0;
```

2024-09-26 14:37 UTC, joywin2003 commented
```Error: to fetch users: q [Error]: Dynamic server usage: Route /api/users couldn't be rendered statically because it used `request.url`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error
    at W (/home/runner/work/website/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:21106)
   Generating static pages (6/13) 
    at Object.get (/home/runner/work/website/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:28459)
    at p (/home/runner/work/website/website/.next/server/app/api/users/route.js:1:649)
    at /home/runner/work/website/website/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36264
    at /home/runner/work/website/website/node_modules/next/dist/server/lib/trace/tracer.js:140:36
    at NoopContextManager.with (/home/runner/work/website/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7062)
    at ContextAPI.with (/home/runner/work/website/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at NoopTracer.startActiveSpan (/home/runner/work/website/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at ProxyTracer.startActiveSpan (/home/runner/work/website/website/node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18854)
    at /home/runner/work/website/website/node_modules/next/dist/server/lib/trace/tracer.js:122:103 {
  description: "Route /api/users couldn't be rendered statically because it used `request.url`. See more info here: https://nextjs.org/docs/messages/dynamic-server-error",
  digest: 'DYNAMIC_SERVER_USAGE'
}```

Getting this error from your admin check in middlware.ts

2024-09-27 15:24 UTC, Vyshnav001 approved these changes
Rest everything looks good for me

2024-09-29 09:36 UTC, joywin2003 commented
then its better to merge it, furthure changes will be done in another PR

2024-09-29 09:36 UTC, merged